# Generated by Django 4.2.7 on 2023-12-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AIcontact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("question", models.TextField()),
                ("answer", models.IntegerField(default=0)),
                ("context", models.TextField()),
            ],
        ),
    ]
