# Generated by Django 4.2.7 on 2023-12-24 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interface", "0003_sendtoccc"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sendtoccc",
            name="number",
        ),
    ]
